image: ebits/openshift-client:v3.11.0

stages:
  - npm
  - analysis
  - sonarqube
  - build

npm_install:
  stage: npm
  tags:
    - ME
  image: centos/nodejs-10-centos7:10
  before_script: []
  script:
    - 'npm install --verbose'
  cache:
    key: modules
    paths:
      - node_modules/

test_lint:
  stage: analysis
  tags:
    - ME
  image: centos/nodejs-10-centos7:10
  before_script: []
  cache:
    key: modules
    paths:
      - node_modules/
    policy: pull
  script:
    - 'npm run lint'

test_unit:
  stage: analysis
  tags:
    - ME
  image: centos/nodejs-10-centos7:10
  before_script: []
  cache:
    key: modules
    paths:
      - node_modules/
    policy: pull
  script:
    - 'npm run lint'

analysis_sonar:
  stage: sonarqube
  tags:
    - ME
  image: sonar-scanner-image:latest
  before_script: []
  script:
    - "sonar-scanner -Dsonar.host.url=http://sonar.fabrica.lifecon.com.br -Dsonar.projectKey=archtype-web -Dsonar.sources='src/app' -Dsonar.projectName=archtype-web -Dsonar.login=d0df9e32ff56ae69e774ecd98285816f5bb13d8f"
  cache:
    key: modules
    paths:
      - node_modules/
    policy: pull

build_app:
  stage: build
  tags:
    - ME
  image: centos/nodejs-10-centos7:10
  before_script: []
  cache:
    key: modules
    paths:
      - node_modules/
    policy: pull
  script:
    - 'npm run build-prod'
  artifacts:
    paths:
      - dist/
