image: ebits/openshift-client:v3.11.0

stages:
  - npm
  - sonarqube
  - analysis
  - build

npm_install:
  stage: npm
  tags:
    - ME
  image: centos/nodejs-10-centos7:10
  before_script: []
  script:
    - 'npm install --verbose'
  cache:
    key: modules
    paths:
      - node_modules/

test_lint:
  stage: analysis
  tags:
    - ME
  image: centos/nodejs-10-centos7:10
  before_script: []
  cache:
    key: modules
    paths:
      - node_modules/
    policy: pull
  script:
    - 'npm run lint'

test_unit:
  stage: analysis
  tags:
    - ME
  image: centos/nodejs-10-centos7:10
  before_script: []
  cache:
    key: modules
    paths:
      - node_modules/
    policy: pull
  script:
    - 'npm run lint'

analysis_sonar:
  stage: sonarqube
  tags:
    - ME
  image: ciricihq/gitlab-sonar-scanner
  variables:
    SONAR_URL: http://sonar.fabrica.lifecon.com.br
    SONAR_ANALYSIS_MODE: publish
  cache:
    key: modules
    paths:
      - node_modules/
    policy: pull
  script:
    - gitlab-sonar-scanner -Dsonar.projectKey=archtype-web -Dsonar.sources=. -Dsonar.host.url=http://sonar.fabrica.lifecon.com.br -Dsonar.login=d0df9e32ff56ae69e774ecd98285816f5bb13d8f

build_app:
  stage: build
  tags:
    - ME
  image: centos/nodejs-10-centos7:10
  before_script: []
  cache:
    key: modules
    paths:
      - node_modules/
    policy: pull
  script:
    - 'npm run build-prod'
  artifacts:
    paths:
      - dist/
